
spring:
  application:
    name: dubbo_server-spring-boot-starter-client
  dubbo:
    registry:
      address: zookeeper://192.168.1.103:2181
    protocol:
      name: dubbo
      port: 20880

server:
  port: 8090
