spring:
  application:
    name: dubbo-auto-configure-consumer-sample
#  thymeleaf:
#    prefix:
dubbo:
  registry:
    address: zookeeper://115.28.234.123:2181?timeout=30000
  application:
    qos-enable: true
    name: consumer
server:
  port: 8090
